# Generated by Django 5.0.6 on 2024-08-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_faculty_id_alter_faculty_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
