# Generated by Django 5.0.6 on 2024-08-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
