# Generated by Django 5.1.1 on 2024-09-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
