# Generated by Django 5.0.6 on 2024-10-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='user_type',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
