# Generated by Django 5.0.6 on 2025-03-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id_no', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('institute', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('cgpa', models.FloatField(max_length=4)),
                ('passing_year', models.IntegerField()),
                ('domains', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('programming_skill', models.CharField(max_length=255)),
                ('tech_skill', models.CharField(max_length=255)),
                ('student_email_id', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='student.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('student', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student.student_details')),
            ],
            options={
                'unique_together': {('student', 'name')},
            },
        ),
    ]
