# Generated by Django 5.1.1 on 2024-09-25 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_auth',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('institute', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('cgpa', models.FloatField(max_length=4)),
                ('passing_year', models.IntegerField()),
                ('domains', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('programming_skill', models.CharField(max_length=255)),
                ('tech_skill', models.CharField(max_length=255)),
            ],
        ),
    ]
