# Generated by Django 5.1.1 on 2024-09-25 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_details_programming_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='certification',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='student_details',
            name='city',
            field=models.CharField(default='changa', max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
