# Generated by Django 5.1.1 on 2024-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_details_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
