# Generated by Django 5.0.6 on 2024-10-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_details_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='phone_no',
        ),
    ]
