# Generated by Django 5.0.6 on 2024-10-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_details_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='id_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
