# Generated by Django 5.1.1 on 2024-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_details_certification_student_details_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='city',
            field=models.CharField(default='Unknown City', max_length=50),
        ),
    ]
