# Generated by Django 5.1.1 on 2024-09-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_details_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='city',
        ),
    ]
