# Generated by Django 5.0.6 on 2024-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_details_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_auth',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
