# Generated by Django 5.1.1 on 2024-09-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_details_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='programming_skill',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='tech_skill',
        ),
    ]
