# Generated by Django 5.1.1 on 2024-09-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_details_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_auth',
            old_name='student_id',
            new_name='id',
        ),
    ]
