# Generated by Django 5.0.6 on 2025-03-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_auth_last_login'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'name')},
        ),
    ]
