# Generated by Django 5.1.1 on 2024-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_details_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='city',
            field=models.CharField(default='Unknown City', max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='programming_skill',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='tech_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
