# Generated by Django 5.0.6 on 2024-08-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_details_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='user',
        ),
    ]
