# Generated by Django 5.1.1 on 2024-09-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_student_id_student_auth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='experiences',
            field=models.CharField(default='No experience', max_length=500),
        ),
    ]
