# Generated by Django 5.0.6 on 2024-09-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_student_details_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
