# Generated by Django 5.1.1 on 2024-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_details_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='experience',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
