# Generated by Django 5.0.6 on 2024-09-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_auth_delete_student_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_no', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('institute', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('cgpa', models.FloatField(max_length=4)),
                ('passing_year', models.IntegerField()),
                ('domains', models.CharField(max_length=255)),
                ('student_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student_auth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
