# Generated by Django 5.0.6 on 2024-09-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='student_auth',
        ),
    ]
