# Generated by Django 5.0.6 on 2024-09-22 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='certification',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='student_details',
            name='city',
            field=models.CharField(default=list, max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='student_details',
            name='programming_skill',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='tech_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
