# Generated by Django 5.0.6 on 2024-09-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_details_certification_student_details_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='city',
            field=models.CharField(default='changa', max_length=50),
        ),
    ]
