# Generated by Django 5.1.1 on 2024-09-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_details_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='experience',
        ),
    ]
