# Generated by Django 5.0.6 on 2024-09-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_student_details_student_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='password',
        ),
    ]
