# Generated by Django 5.0.6 on 2024-10-05 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='student.student_auth'),
        ),
    ]
