# Generated by Django 5.0.6 on 2024-10-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_student_details_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='user',
        ),
    ]
