# Generated by Django 5.1.1 on 2024-10-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_student_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
