# Generated by Django 5.0.6 on 2024-08-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
