# Generated by Django 5.0.6 on 2024-08-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_faculty_details_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_details',
            name='user',
        ),
    ]
