# Generated by Django 5.0.6 on 2025-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_rename_faculty_details_faculty_auth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_details',
            fields=[
                ('faculty_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='faculty_auth',
            old_name='faculty_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='faculty_auth',
            name='name',
        ),
        migrations.AlterField(
            model_name='faculty_auth',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
