# Generated by Django 5.0.6 on 2025-03-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_facultyfcmtoken_studentfcmtoken'),
        ('student', '0006_alter_certificate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfcmtoken',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_details'),
        ),
    ]
