# Generated by Django 5.0.6 on 2025-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_alter_studentfcmtoken_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfcmtoken',
            name='student',
        ),
        migrations.AddField(
            model_name='studentfcmtoken',
            name='student_idno',
            field=models.CharField(default='00', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
