# Generated by Django 5.0.6 on 2025-03-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_remove_studentfcmtoken_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfcmtoken',
            name='student_idno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='studentfcmtoken',
            unique_together={('student_idno', 'token')},
        ),
    ]
