# Generated by Django 5.0.6 on 2025-02-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_alter_student_auth_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.CharField(max_length=255, null=True)),
                ('headquarters', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('details', models.TextField(null=True)),
                ('date_placementdrive', models.DateField(null=True)),
                ('application_deadline', models.DateField(null=True)),
                ('joining_date', models.DateField(null=True)),
                ('hr_name', models.CharField(max_length=255, null=True)),
                ('hr_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('hr_contact', models.CharField(max_length=15, null=True)),
                ('bond', models.IntegerField(null=True)),
                ('benefits', models.CharField(max_length=255, null=True)),
                ('doc_required', models.CharField(max_length=255, null=True)),
                ('process_stages', models.CharField(max_length=255, null=True)),
                ('eligibility_criteria', models.CharField(max_length=255, null=True)),
                ('no_round', models.IntegerField()),
                ('cutoff_marks', models.CharField(max_length=200, null=True)),
                ('selection_ratio', models.CharField(max_length=20, null=True)),
                ('duration_internship', models.CharField(max_length=20, null=True)),
                ('stipend', models.IntegerField(null=True)),
                ('job_role', models.CharField(max_length=255, null=True)),
                ('job_description', models.CharField(max_length=255, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('job_location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=20, null=True)),
                ('min_package', models.BigIntegerField()),
                ('max_package', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_unique_id', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='student.student_details')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('running', 'Running')], default='pending', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='company.companydetails')),
            ],
            options={
                'unique_together': {('company', 'round_name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_students', to='company.companydetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_registrations', to='student.student_details')),
            ],
            options={
                'unique_together': {('student', 'company')},
            },
        ),
        migrations.CreateModel(
            name='StudentInterviewProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False)),
                ('is_present', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='company.companydetails')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='company.interviewround')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_progress', to='student.student_details')),
            ],
            options={
                'unique_together': {('student', 'company', 'round')},
            },
        ),
    ]
