# Generated by Django 5.1.1 on 2024-09-28 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('comapny_name', models.CharField(max_length=255)),
                ('company_website', models.CharField(max_length=255)),
                ('headquarters', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('date_placementdrive', models.DateField()),
                ('application_deadline', models.DateField()),
                ('joining_date', models.DateField()),
                ('hr_name', models.CharField(max_length=255)),
                ('hr_email', models.EmailField(max_length=254, unique=True)),
                ('hr_contact', models.CharField(max_length=15)),
                ('bond', models.IntegerField(null=True)),
                ('benefits', models.CharField(max_length=255)),
                ('doc_required', models.CharField(max_length=255)),
                ('process_stages', models.CharField(max_length=255)),
                ('eligibility_criteria', models.CharField(max_length=255)),
                ('no_round', models.IntegerField()),
                ('cutoff_marks', models.CharField(max_length=200)),
                ('selection_ratio', models.CharField(max_length=20)),
                ('duration_internship', models.CharField(max_length=20)),
                ('stipend', models.IntegerField()),
                ('job_role', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('job_salary', models.IntegerField()),
                ('job_type', models.CharField(max_length=20)),
                ('min_package', models.BigIntegerField()),
                ('max_package', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('running', 'Running')], default='pending', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='company.companydetails')),
            ],
            options={
                'unique_together': {('company', 'round_number')},
            },
        ),
    ]
