# Generated by Django 5.0.6 on 2024-08-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('comapny_name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('min_package', models.BigIntegerField()),
                ('max_package', models.BigIntegerField()),
                ('bond', models.IntegerField(null=True)),
                ('comapny_hq_location', models.CharField(max_length=255)),
                ('work_locations', models.CharField(max_length=255)),
                ('comapny_web', models.CharField(max_length=255)),
                ('company_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recruiter_name', models.CharField(max_length=255)),
                ('recruiter_email', models.EmailField(max_length=254)),
                ('form_last_date', models.DateTimeField()),
                ('form_filled', models.IntegerField()),
                ('venue', models.CharField(max_length=255)),
                ('no_of_rounds', models.SmallIntegerField()),
                ('form_start_date', models.DateTimeField()),
                ('no_of_student', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companydetails')),
            ],
        ),
    ]
