# Generated by Django 5.0.6 on 2024-08-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyPlacementDrive',
        ),
    ]
