# Generated by Django 5.1.1 on 2024-10-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='job_salary',
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='application_deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='benefits',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='cutoff_marks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='date_placementdrive',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='doc_required',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='duration_internship',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='eligibility_criteria',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='headquarters',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='hr_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='hr_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='hr_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='job_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='job_role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='process_stages',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='selection_ratio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='stipend',
            field=models.IntegerField(null=True),
        ),
    ]
