# Generated by Django 5.0.6 on 2024-10-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companydetails_job_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='job_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
