# Generated by Django 5.1.1 on 2025-02-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyregistration_company_name_and_more'),
        ('student', '0005_alter_student_auth_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='sortlisted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_no', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortlisted_students', to='company.companydetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortlisted_registrations', to='student.student_details')),
            ],
            options={
                'unique_together': {('student', 'company')},
            },
        ),
    ]
