# Generated by Django 5.0.6 on 2024-08-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delete_companyplacementdrive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
    ]
