# Generated by Django 5.0.6 on 2024-10-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companydetails_job_type'),
        ('student', '0005_alter_student_auth_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_students', to='company.companydetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_registrations', to='student.student_auth')),
            ],
            options={
                'unique_together': {('student', 'company')},
            },
        ),
    ]
