# Generated by Django 5.0.6 on 2025-02-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_sortlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='date_placementdrive',
        ),
    ]
