# Generated by Django 5.0.6 on 2024-09-28 14:25

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='company_contact',
            field=models.CharField(max_length=15),
        ),
    ]
