# Generated by Django 5.0.6 on 2024-10-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyregistration'),
        ('student', '0005_alter_student_auth_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_registrations', to='student.student_details'),
        ),
    ]
