# Generated by Django 5.0.6 on 2024-10-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyregistration_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
