# Generated by Django 5.0.6 on 2024-09-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companydetails_company_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('running', 'Running'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='company.companydetails')),
            ],
            options={
                'unique_together': {('company', 'round_number')},
            },
        ),
    ]
