# Generated by Django 5.0.6 on 2025-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companydetails_date_placementdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='job_description',
            field=models.CharField(default='There is nothing for now', max_length=255),
            preserve_default=False,
        ),
    ]
