# Generated by Django 5.0.6 on 2025-02-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companydetails_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='company_images/')),
            ],
        ),
    ]
