# Generated by Django 5.0.6 on 2024-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_interviewround'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='company_contact',
        ),
        migrations.RemoveField(
            model_name='interviewround',
            name='scheduled_date',
        ),
        migrations.AlterField(
            model_name='interviewround',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('running', 'Running')], default='pending', max_length=10),
        ),
    ]
