# Generated by Django 5.0.6 on 2025-02-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companyimages'),
        ),
    ]
