# Generated by Django 5.0.6 on 2025-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companydetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='no_round',
        ),
        migrations.AddField(
            model_name='interviewround',
            name='index',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
