# Generated by Django 5.0.6 on 2025-02-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_companydetails_no_round_interviewround_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewround',
            name='index',
            field=models.IntegerField(),
        ),
    ]
