# Generated by Django 5.0.6 on 2025-03-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_interviewround_index'),
        ('student', '0006_alter_certificate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinterviewprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentinterviewprogress',
            name='round_index',
            field=models.IntegerField(default='10'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentinterviewprogress',
            unique_together={('student', 'company', 'round_index')},
        ),
    ]
