# Generated by Django 5.0.6 on 2025-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_studentinterviewprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInterviewProgress',
        ),
    ]
