# Generated by Django 5.0.6 on 2025-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_delete_studentinterviewprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='application_deadline',
            field=models.DateField(default='01-01-2000'),
            preserve_default=False,
        ),
    ]
