# Generated by Django 5.0.6 on 2025-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_companydetails_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='application_deadline',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
